config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :characters
  resources :games
  resources :matches
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users_admin, only: [:index], :controller => 'users'
  resources :articles
  resources :topics, only: [:show]
  root to: 'pages#news'
  get 'faq', to: 'pages#faq'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :topic
  validates_presence_of :title, :body, :topic_id

  mount_uploader :thumb_image, ArticleUploader
  mount_uploader :main_image, ArticleUploader

  def self.featured_news
    limit(4)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_topics, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @topic = @article.topic
  end

  # GET /articles/new
  def new
    @article = Article.new
    authorize @article
  end

  # GET /articles/1/edit
  def edit
    authorize @article
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    authorize @article

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    authorize @article
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    authorize @article
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def set_topics
    @topics = Topic.all
  end

  def article_params
    params.require(:article).permit(:title, :body, :main_image, :thumb_image, :topic_id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 15, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :topic %>
    <%= form.select :topic_id, Topic.all.collect { |topic| [ topic.title, topic.id ] }, include_blank: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :main_image %>
    <%= form.file_field :main_image %>
  </div>

  <div class="form-group">
    <%= form.label :thumb_image %>
    <%= form.file_field :thumb_image %>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit', class: 'btn btn-dark' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container">
  <% if policy(@articles).new? %>
    <%= link_to fa_icon('file'), new_article_path %>
  <% end %>
  <hr>
  <div class="row text-center">
    <% if @articles.count != 0 %>
      <%= render partial: 'shared/article', collection: @articles, locals: {height: 'auto', width: '100%'} %>
    <% else %>
      <h3>There is no news at the moment</h3>
    <% end %>
  </div>
  <hr>
</div>

app/views/articles/new.html.erb
<div class="container">

  <h1>New Article</h1>

  <%= render 'form', article: @article %>

  <%= link_to 'Back', articles_path, class: 'btn btn-dark' %>

</div>

app/views/articles/show.html.erb
<div class="container article-container">
  <div class="row">
    <% if @article.main_image.url != nil %>
      <div class="col-md-12">
        <%= image_tag @article.main_image.url, width: '100%' %>
      </div>
    <% end %>
  </div>
  <div class="row"></div>
    <div class="col-md-12">
      <h1>
        <%= @article.title %>
        <small>
          <% if policy(@article).update? %>
            <%= link_to fa_icon('pencil'), edit_article_path(@article), :style=>'color:#FFFFFF;' %>
            <%= link_to fa_icon('trash'), @article, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </small>
      </h1>

      <nav class="breadcrumb">
        <%= link_to 'Home', root_path, class: 'breadcrumb-item' %>
        <%= link_to 'News', articles_path, class: 'breadcrumb-item' %>
        <%= link_to @article.topic.title, topic_path(@topic), class: 'breadcrumb-item' %>

        <span class="breadcrumb-item active"><%= @article.title %></span>

      </nav>

      <p><%= markdown @article.body %></p>
    </div>
  </div>
</div>