config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :characters
  resources :games
  resources :matches
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users_admin, only: [:index], :controller => 'users'
  resources :articles
  resources :topics, only: [:show]
  root to: 'pages#news'
  get 'faq', to: 'pages#faq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :topic
  validates_presence_of :title, :body, :topic_id

  mount_uploader :thumb_image, ArticleUploader
  mount_uploader :main_image, ArticleUploader

  def self.featured_news
    limit(4)
  end

end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :matches
  has_many :characters
end

app/models/guest_user.rb
class GuestUser < User
  attr_accessor :username, :email
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :game
  belongs_to :user

  def self.featured_matches
    limit(6)
  end
end

app/models/player.rb
class Player < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  has_many :matches

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]

  def index
    @games = Game.all
  end

  def show
    @recent_vods = @game.matches.order('created_at DESC').limit(4)
  end

  def new
    @game = Game.new
    authorize @game
  end

  def edit
    authorize @game
  end

  def create
    @game = Game.new(game_params)
    authorize @game

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    authorize @game

    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    authorize @game

    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:title, :description, :cover_image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def news
    @articles = Article.all.featured_news
    @matches = Match.all.featured_matches
  end

  def faq
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def show
    @topic = Topic.find(params[:id])

    @articles = @topic.articles.all

  end

  def create
    authorize @topic
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:match).permit(:username, :steamid, :psnid, :gamertag, :switchfc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper style = ''
    if current_user.is_a?(GuestUser)
      (link_to "Register", new_user_registration_path, class: style) +
      " ".html_safe +
      (link_to "Login", new_user_session_path, class: style)
    else
      (link_to "Edit My Details", edit_user_registration_path,class: style) +
      " ".html_safe +
      (link_to "Logout", destroy_user_session_path, method: :delete, class: style)
    end
  end

  def nav_items
    [
      {
        url: root_path,
        title: 'Home'
      },
      {
        url: games_path,
        title: 'Games'
      },
      {
        url: topic_path(1),
        title: 'Articles'
      },
      {
        url: topic_path(2),
        title: 'Events'
      },
      {
        url: matches_path,
        title: 'Match Database'
      },
      {
        url: users_admin_index_path,
        title: 'Local Player Profiles'
      },
      {
        url: faq_path,
        title: 'FAQ'
      }
    ]
  end

  def nav_helper style, tag_type

    nav_links = ''

    nav_items.each do |item|
      nav_links << "<#{tag_type}><a href='#{item[:url]}' class='#{style} #{active? item[:url]}'>#{item[:title]}</a></#{tag_type}>"
    end

    nav_links.html_safe
  end

  def active? path
    "active" if current_page? path
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/character_helper.rb
module CharacterHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="turbolinks-cache-control" content="no-cache">

    <title>JUSTPRESS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag 'favicons/favicon.ico' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-8288199828592912",
        enable_page_level_ads: true
      });
    </script>

  </head>

  <body>

      <%= render "shared/application_nav"%>

      <div class="fluid-container">
        <%= yield %>
      </div>

      <%= render "shared/application_footer" %>

  </body>
</html>

app/views/pages/faq.html.erb
<h1>FAQ</h1>
<h2>Table Of Contents</h2>
<ol>
  <li><a href="#How to link to specific matches on twitch vods">How to link to specific matches on twitch vods</a></li>
  <li><a href="#How to link to specific matches on youtube">How to link to specific matches on youtube</a></li>
  <li><a href="#Can anyone add matches to the database?">Can anyone add matches to the database?</a></li>
  <li><a href="#Can anyone add players to the database?">Can anyone add players to the database?</a></li>
  <li><a href="#I found an incorrect link/duplicate entry of a footage, what do?">I found an incorrect link/duplicate entry of a footage, what do?</a></li>
  <li><a href="#I no longer go by the name the69king and would like it changed on the database.">I no longer go by the name the69king and would like it changed on the database.</a></li>
  <li><a href="#I need the list of moderators I can bother on discord.">I need the list of moderators I can bother on discord.</a></li>
  <li><a href="#Will more features be added to the website?">Will more features be added to the website?</a></li>
  <li><a href="#I want to be a moderator and help run the site.">I want to be a moderator and help run the site.</a></li>
  <li><a href="#I want to be an editor and write articles for the site.">I want to be an editor and write articles for the site.</a></li>
  <li><a href="#I want to help design a logo or something for the site.">I want to help design a logo or something for the site.</a></li>
  <li><a href="#What is the purpose of this website?">What is the purpose of this website?</a></li>
  <li><a href="#I didn't know there was a discord where members of the safgc organize matches, I want to join.">I didn't know there was a discord where members of the safgc organize matches, I want to join.</a></li>

</ol>

<h2 id="How to link to specific matches on twitch vods">How to link to specific matches on twitch vods</h2>
<p align="justify">Just add ?t=_h_m_s to the end of the url. Fill in the blanks with the timestamp.
    For example, if you want to link to a spot that is at 01:18:42, your link would look like:
    https://www.twitch.tv/videos/478610916?t=01h18m42s
    You can also drop starting zeros, so 01:29:19 could also look like ?t=1h29m19s.
    If the time is at 19:51, the link could use ?t=19m51s.<br></p>

<h2 id="How to link to specific matches on youtube">How to link to specific matches on youtube</h2>
<p align="justify">Click the share button, then tick the 'start at' checkbox and copy/ paste the url generated<br></p>

<h2 id="Can anyone add matches to the database?">Can anyone add matches to the database?</h2>
<p align="justify">Any user that is signed in can add matches to the user database. So add any footage you know of that isn't already in the database and contact me (pdivvie) or a moderator on the safgc discord if the players involved are not listed.<br></p>

<h2 id="Can anyone add players to the database?">Can anyone add players to the database?</h2>
<p align="justify">For now only moderators can add players to the website. This is to prevent, as far as possible, duplicate entries of the same players and thus segmenting their footage unnecessarily.<br></p>

<h2 id="I found an incorrect link/duplicate entry of a footage, what do?">I found an incorrect link/duplicate entry of a footage, what do?</h2>
<p align="justify">Contact myself(pdivvie) or any moderator on discord to remove the duplicate entry/ fix the link.<br></p>

<h2 id="I no longer go by the name the69king and would like it changed on the database.">I no longer go by the name the69king and would like it changed on the database.</h2>
<p align="justify">Contact myself(pdivvie) or any moderator on discord.<br></p>

<h2 id="I need the list of moderators I can bother on discord.">I need a list of moderators I can bother on discord.</h2>
<p align="justify">@pdivvie<br></p>

<h2 id="Will more features be added to the website?">Will more features be added to the website?</h2>
<p align="justify">I have more features planned for the website but whether or not I continue to work on the website will depend on whether the community makes use of it or not. Some features I want to implement are: <br><br>

  1. Sorting/ searching matches by in-game characters.<br>
  2. Sorting players into categories for the games they play to narrow down the list of players to choose from when linking to new footage.<br>
  3. A section where users can write their own articles (already on the site but no editors).<br>
  4. A section where moderators can update the site with the latest events and announcements (already on the site but no moderators).<br>
  5. A section where users can create 'dummy tournaments' with a lower limit of players to guage interest before committing to tournament organizing (if not enough players indicate interest before a certain date the tournament doesnt happen). Could be nice for arranging small casual but regular online tourneys.<br><br>

  DM me on discord if you have any other ideas you'd like to share or just to let me know you are making use of the site. Your interest shows me that the site is worth working on<br></p>

<h2 id="I want to be a moderator and help run the site.">I want to be a moderator and help run the site.</h2>
<p align="justify">DM me(pdivvie) on the safgc discord if you would like to be a moderator. You should be fairly active in the scene to know the players as one of your tasks will be to add players to the database without producing duplicates where possible. People frequently change the name they go by so it helps if you've been in the scene long enough to know that i.e. 420wheatit now goes by the69king etc.<br></p>

<h2 id="I want to be an editor and write articles for the site.">I want to be an editor and write articles for the site.</h2>
<p align="justify">DM me(pdivvie) on the safgc discord if you would like to be an editor.<br></p>

<h2 id="I want to help design a logo or something for the site.">I want to help design a logo or something for the site.</h2>
<p align="justify">La Volpe pls.<br></p>

<h2 id="What is the purpose of this website?">What is the purpose of this website?</h2>
<p align="justify">This website was made for use by anyone who is involved in the competitive fighting games in South Africa. The primary purpose of it is:<br>
  1. Boost the strength of the local competitive fighting game scene by:<br>
    1.a Creating a database of LOCAL MATCH FOOTAGE so that players can learn by studying player matchups instead of just character matchups (or just watch local footage for entertainment purposes).<br>
    1.b Have easy access to all your own recorded matches in one place to learn from.<br><br>

The secondary purposes of the website is:<br>
  1. To create a database of USERS and their details so players can network more by adding each other and ask for games.<br>
  2. To create a hub where players can look for news, articles and events.<br>
  3. To create a hub where players can go to organize tournaments.<br><br></p>

<h2 id="I didn't know there was a discord where members of the safgc organize matches, I want to join.">I didn't know there was a discord where members of the safgc organize matches, I want to join.</h2>
<p align="justify"><%= link_to 'SAFGC Discord', 'https://discord.gg/BzyYPQ', class: 'btn btn-dark', target: :_blank %> <- Need a permanent link for this<br></p>




app/views/pages/news.html.erb
<div class="container">

  <% if current_user.is_a?(GuestUser) %>
    <header class="jumbotron my-4">
      <h1 class="display-3">JUST PRESS</h1>
      <p class="lead">This site is designed to give the local fighting game community a place to gather for news updates such as events but most importantly to share/ watch local vods of past matches. Feel free to register if you would like other players to be able to connect with you and add vods. </p>
      <%= link_to "Register", new_user_registration_path,class: 'btn btn-dark btn-lg' %>
    </header>
  <% end %>

  <div class="frontpage-heading">
    <h4>Latest News</h4>
  </div>
  <div class="row text-center">
    <% if @articles.count != 0 %>
      <%= render partial: 'shared/article', collection: @articles, locals: {height: '200px', width: '100%'} %>
    <% else %>
      <div class="col-12">
        <h3>There is no news at the moment</h3>
      </div>
    <% end %>
  </div>

  <hr>

  <div class="frontpage-heading">
    <h4>Latest Matches</h4>
  </div>

  <div class="card matches-card d-none d-lg-block">
    <% @matches.order('created_at DESC').each do |match| %>
      <%= render partial: 'shared/matches_desktop', locals: { match: match } %>
    <% end %>
  </div>
  

  <div class="card matches-card d-none d-block d-lg-none">
    <% @matches.order('created_at DESC').each do |match| %>
      <%= render partial: 'shared/matches_mobile', locals: { match: match } %>
    <% end %>
  </div>

</div>

app/views/shared/_application_footer.html.erb
<div class="footer">
  <footer class="py-1 bg-dark fixed-bottom">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; JUSTPRESS 2019</p>
    </div>
    <!-- /.container -->
  </footer>
</div>

app/views/shared/_application_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">JUSTPRESS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <%= nav_helper 'nav-link', 'span' %>
        <%= login_helper 'nav-link' %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_article.html.erb
<div class="col-lg-3 col-md-6 mb-4">
  <div class="card h-100">
    <% if article.thumb_image.url != nil %>
      <%= image_tag article.thumb_image.url, height: height, width: width %>
    <% end %>
    <div class="card-body">
      <h4 class="card-title"><%= article.title %></h4>
      <p class="card-text"><%= truncate(article.body, :length => 200) %></p>
    </div>
    <div class="card-footer">
      <span><%= link_to 'Find Out More!', article_path(article), class: 'btn btn-dark' %></span>
    </div>
  </div>
</div>

app/views/shared/_matches_desktop.html.erb
<div class="row">
  <div class="col-md-2">
    <div class="p-alt2">
      <p><%= link_to match.game.title, game_path(match.game_id) unless match.game_id == nil %></p>
    </div>
  </div>

  <div class="col-md-2">
    <% if match.p1_name != nil %>
      <div class="p-alt">
        <p><%= link_to match.p1_name, matches_path(P1: match.p1_name) %><p>
      </div>
    <% else %>
      Unknown Player
    <% end %>
  </div>

  <div class="col-md-1">
    <% if match.p1_character != nil %>
      <div class="avatar">
        <%= image_tag(match.p1_character, size: 64) %>
      </div>
    <% else %>
      Unknown Character
    <% end %>
  </div>

  <div class="col-md-1">
    <div class="p-alt">
      <p>vs</p>
    </div>
  </div>

  <div class="col-md-1">
    <% if match.p2_character != nil %>
      <div class="avatar">
        <%= image_tag(match.p2_character, size: 64) 
        %>
      </div>
    <% else %>
      Unknown Character
    <% end %>
  </div>

  <div class="col-md-2">
    <% if match.p2_name != nil %>
    <div class="p-alt">
      <p><%= link_to match.p2_name, matches_path(P1: match.p2_name) %><p>
    </div>
    <% else %>
      Unknown Player
    <% end %>
  </div>

  <div class="col-md-3">
    <div class="p-alt3">
      <%= link_to fa_icon('play'), match.link, target: :_blank %>
      <% if policy(match).update? %>
        <%= link_to fa_icon('pencil'), edit_match_path(match) %>
        <%= link_to fa_icon('trash'), match, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
</div>

<hr>

app/views/shared/_matches_mobile.html.erb
<div class="row">
  <div class="col-9">
    <div class="row">
      <div class="col-3">
        <% if match.p1_character != nil %>
          <div class="avatar">
            <%= image_tag(match.p1_character, size: 64) %>
          </div>
        <% else %>
          Unknown Character
        <% end %>
      </div>
      <div class="col-9">
        <% if match.p1_name != nil %>
          <div class="p-alt">
            <p><%= link_to match.p1_name, matches_path(P1: match.p1_name) %><p>
          </div>
        <% else %>
          Unknown Player
        <% end %>
      </div>
    </div>

    <br>

    <div class="row">
      <div class="col-3">
        <% if match.p2_character != nil %>
          <div class="avatar">
            <%= image_tag(match.p2_character, size: 64) %>
          </div>
        <% else %>
          Unknown Character
        <% end %>
      </div>
      <div class="col-9">
        <% if match.p2_name != nil %>
          <div class="p-alt">
            <p><%= link_to match.p2_name, matches_path(P1: match.p2_name) %><p>
          </div>
        <% else %>
          Unknown Player
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-3">
    <div class="row">
      <div class="col-12">
        <% if policy(match).update? %>
          <%= link_to fa_icon('pencil'), edit_match_path(match) %>
        <% else%>
        <br>
        <% end %>
      </div>
    </div>

    <br>

    <div class="row">
      <div class="col-12"><%= link_to fa_icon('play'), match.link, target: :_blank %></div>
    </div>

    <br>

    <div class="row">
      <div class="col-12">
        <% if policy(match).update? %>
          <%= link_to fa_icon('trash'), match, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
  </div>

</div>

<hr>