config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :characters
  resources :games
  resources :matches
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users_admin, only: [:index], :controller => 'users'
  resources :articles
  resources :topics, only: [:show]
  root to: 'pages#news'
  get 'faq', to: 'pages#faq'
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :matches
  has_many :characters
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]

  def index
    @games = Game.all
  end

  def show
    @recent_vods = @game.matches.order('created_at DESC').limit(4)
  end

  def new
    @game = Game.new
    authorize @game
  end

  def edit
    authorize @game
  end

  def create
    @game = Game.new(game_params)
    authorize @game

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    authorize @game

    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    authorize @game

    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:title, :description, :cover_image)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :cover_image %>
    <%= form.text_field :cover_image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit', class: 'btn btn-dark' %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div class="container">
  <% if policy(@games).new? %>
    <%= link_to fa_icon('gamepad'), new_game_path %>
    <hr>
  <% end %>

  
    <% @games.each_with_index do |game, i| %>
      <% if i%2 == 0 %>
        <div class="row">
      <% end %> 

      <div class="col-md-6">

        <div class="d-none d-xl-block">
          <div class="card">
            <%= link_to game, class: 'image_link' do %>
              <%= image_tag game.cover_image, class: 'card-img-top img-fluid' %>

              <div class="image_icon">
                <% if policy(game).update? %>
                  <%= link_to fa_icon('pencil'), edit_game_path(game) %>
                  <%= link_to fa_icon('trash'), game, method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>

        <div class="d-none d-block d-xl-none">
          <div class="card img-fluid" style="height:190px">
            <%= link_to game, class: 'image_link' do %>
              <%= image_tag game.cover_image, class: 'style_image_mobile' %>
              <div class="card-img-overlay image_text" >
                <h4 class="card-title"><%= game.title %></h4>
                <br>

              </div>

              <div class="image_icon_mobile">
                <% if policy(game).update? %>
                  <%= link_to fa_icon('pencil'), edit_game_path(game) %>
                  <%= link_to fa_icon('trash'), game, method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </div>
            <% end %>
          </div>
          <br>
        </div>

      <br>
      <br>

      </div>

      <br>
      <% if i%2 != 0 %>
        </div>
      <% end %>
    <% end %>
  
</div>

app/views/games/new.html.erb
<div class="container">

  <h1>New Game</h1>

  <%= render 'form', game: @game %>

  <%= link_to 'Back', games_path, class: 'btn btn-dark' %>

</div>

app/views/games/show.html.erb
<div class="card img-fluid" style="width:1400px">
  <img class="card-img-top d-none d-xl-block" src=<%= @game.cover_image %> alt="Card image" style="height:100%">
  <div class="card-img-overlay">
    <div class="card-text">
      <h4 class="card-title"><%= @game.title %></h4>
      <p class="d-none d-xl-block"><%= @game.description %></p>
    </div>  
    <p><a href="#" class="btn btn-secondary">Resources</a></p>
    <p><%= link_to 'Local Matches', matches_path(game_query: @game.id), class: 'btn btn-secondary' %></p>
    <p><a href="#" class="btn btn-secondary">Events</a></p>
    <br>
    <br>
    <br>
    <h4>Recent Matches</h4>
    <hr>
    <div class="card matches-card d-none d-lg-block">
      <% @recent_vods.each do |match| %>
        <%= render partial: 'shared/matches_desktop', locals: { match: match } %>
      <% end %>
    </div>

    <div class="card matches-card d-none d-block d-lg-none">
      <% @recent_vods.each do |match| %>
        <%= render partial: 'shared/matches_mobile', locals: { match: match } %>
      <% end %>
    </div>
  </div>
</div>