config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :characters
  resources :games
  resources :matches
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :users_admin, only: [:index], :controller => 'users'
  resources :articles
  resources :topics, only: [:show]
  root to: 'pages#news'
  get 'faq', to: 'pages#faq'
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :game
  belongs_to :user

  def self.featured_matches
    limit(6)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create]

  def index
    if params.has_key?(:game_query)
      @game_query = Match.find_by_game_id(params[:game_query])
      @game_id = @game_query.game_id
      @matches = Match.all.where(game_id: @game_id)
    elsif params.has_key?(:P1)
      @P1 = Player.find_by_username(params[:P1])
      @P1user = @P1.username
      @matches = Match.where("p1_name = ? OR p2_name = ?", @P1user, @P1user)
    elsif params.has_key?(:C1)
      @C1 = Character.find_by_title(params[:C1])
      @C1icon = @C1.icon
      @matches = Match.where("p1_character = ? OR p2_character = ?", @C1icon, @C1icon)
    else
      @matches = Match.all
    end

    @players = Player.all
    @characters = Character.all
  end

  def show
  end

  def new
    @match = Match.new
  end

  def edit
    authorize @match
  end

  def create
    @match = Match.new(match_params)
    @match.user_id = current_user.id

    respond_to do |format|
      if @match.save
        format.html { redirect_to matches_url, notice: 'Match was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    authorize @match

    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to matches_url, notice: 'Match was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    authorize @match

    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
    end
  end

  private
  def set_match
    @match = Match.find(params[:id])
  end

  def match_params
    params.require(:match).permit(:link, :game_id, :user_id, :p1_name, :p2_name, :p1_character, :p2_character)
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_with(model: match, local: true) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= link_to 'How to link vods with timestamps', faq_path, target: :_blank, class: 'btn btn-dark' %>
  </div>

  <div class="form-group">
    <%= form.label :link %>
    <%= form.text_field :link, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :game_id %>
    <%= form.collection_select(:game_id, Game.all, :id, :title,
                                {
                                  selected: match.game_id,
                                  include_blank: true
                                },
                                class: 'form-control'
                              )
    %>
  </div>

  <div class="row">

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label "Select Player 1" %>
        <%= form.select :p1_name, Player.all.order('username ASC').collect { |player| [ player.username, player.username ] }, include_blank: true, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label "Player 1 Character" %>
        <%= form.select :p1_character, Character.all.order('title ASC').collect { |character| [ character.title, character.icon ] }, include_blank: true, class: 'form-control' %>
      </div>
    </div>

  </div>

  <div class="row">

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label "Select Player 2" %>
        <%= form.select :p2_name, Player.all.order('username ASC').collect { |player| [ player.username, player.username ] }, include_blank: true, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label "Player 2 Character" %>
        <%= form.select :p2_character, Character.all.order('title ASC').collect { |character| [ character.title, character.icon ] }, include_blank: true, class: 'form-control' %>
      </div>
    </div>

  </div>

  


  <div class="form-group">
    <%= form.submit 'Submit', class: 'form-control' %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<%= link_to fa_icon('plus'), new_match_path %>
<% if policy(@players).new? %>
  <%= link_to fa_icon('user-plus'), new_player_path %>
<% end %>
<% if policy(@players).destroy? %>
  <%= link_to fa_icon('user'), players_path %>
<% end %>
<% if policy(@characters).destroy? %>
  <%= link_to fa_icon('drupal'), characters_path %>
<% end %>

<hr>

<nav class="breadcrumb">
  <%= link_to 'Match Database', matches_path, class: 'breadcrumb-item' %>
  <span class="breadcrumb-item active">Matches</span>

  <span class="ml-auto">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Select A Game
      </a>
      <div class="dropdown-menu scrollable-menu" aria-labelledby="navbarDropdownMenuLink">
        <% Game.order('title ASC').each do |game| %>
          <%= link_to game.title, matches_path(game_query: game.id), class: "dropdown-item" %>
        <% end %>
      </div>
    </li>
  </span>

  
    <span class="ml-auto">
    <% if params.has_key?(:game_query) %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Select A Character</a>
        <div class="dropdown-menu scrollable-menu" aria-labelledby="navbarDropdownMenuLink">
          <% Character.order('title ASC').each do |character| %>
            <% if character.game_id == @game_query.game_id %>      
              <%= link_to character.title, matches_path(C1: character.title), class: "dropdown-item" %>
            <% end %>
          <% end %>
        </div>
      </li>
      <% end %>
    </span>
    

  <span class="ml-auto">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Select A Player
      </a>
      <div class="dropdown-menu scrollable-menu" aria-labelledby="navbarDropdownMenuLink">
        <% Player.order('username ASC').each do |player| %>
          <%= link_to player.username, matches_path(P1: player.username ), class: "dropdown-item" %>
        <% end %>
      </div>
    </li>
  </span>
</nav>

<div class="card matches-card d-none d-lg-block">
  <% @matches.order('created_at DESC').each do |match| %>
    <%= render partial: 'shared/matches_desktop', locals: { match: match } %>
  <% end %>
</div>

<div class="card matches-card d-none d-block d-lg-none">
  <% @matches.order('created_at DESC').each do |match| %>
    <%= render partial: 'shared/matches_mobile', locals: { match: match } %>
  <% end %>
</div>

app/views/matches/new.html.erb
<div class="container">

  <h1>New Match</h1>

  <%= render 'form', match: @match %>

  <%= link_to 'Back', matches_path, class: 'btn btn-dark' %>

</div>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @match.link %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>